-- +goose Up
-- Создаем ENUM-типы (если используются)
CREATE TYPE usersettings_theme_enum AS ENUM ('dark', 'light');
CREATE TYPE usersettings_notificationlevel_enum AS ENUM ('all', 'mentions', 'none');

-- Создаем таблицы
CREATE TABLE "UserActivityLogs" (
  "LogID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" int,
  "ActivityType" varchar(100),
  "ActivityDescription" text,
  "ActivityTimestamp" timestamp
);

CREATE TABLE "ChannelMembers" (
  "ChannelID" int,
  "UserID" int,
  "JoinedAt" timestamp
);

CREATE TABLE "UserRoles" (
  "UserID" int,
  "RoleID" int,
  "AssignedAt" timestamp,
  "AssignedBy" integer
);

CREATE TABLE "MessageReactions" (
  "ReactionID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MessageID" int,
  "UserID" int,
  "ReactionType" varchar(50),
  "CreatedAt" timestamp
);

CREATE TABLE "DirectMessages" (
  "DirectMessageID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SenderID" int,
  "ReceiverID" int,
  "MessageText" text,
  "CreatedAt" timestamp
);

CREATE TABLE "AppRoles" (
  "RoleID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RoleName" varchar(100)
);

CREATE TABLE "Files" (
  "FileID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" int,
  "FileName" varchar(255),
  "FileSize" int,
  "FileType" varchar(50),
  "CreatedAt" timestamp
);

CREATE TABLE "UserSettings" (
  "UserID" int PRIMARY KEY,
  "Theme" usersettings_theme_enum,
  "NotificationLevel" usersettings_notificationlevel_enum,
  "app settings array" varchar
);

CREATE TABLE "Users" (
  "UserID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Username" varchar(50) UNIQUE NOT NULL,
  "Email" varchar(100) UNIQUE NOT NULL,
  "PasswordHash" char(64) NOT NULL,
  "CreatedAt" timestamp,
  "LastLogin" timestamp,
  "IsActive" boolean
);

CREATE TABLE "AppSettings" (
  "SettingID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SettingName" varchar(100),
  "SettingValue" varchar(255)
);

CREATE TABLE "FileMessages" (
  "FileMessageID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FileID" int,
  "MessageID" int
);

CREATE TABLE "Channels" (
  "ChannelID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ChannelName" varchar(100) NOT NULL,
  "IsPrivate" boolean,
  "CreatedAt" timestamp
);

CREATE TABLE "UserMentions" (
  "MentionID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MessageID" int,
  "UserID" int,
  "MentionedAt" timestamp
);

CREATE TABLE "Messages" (
  "MessageID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ChannelID" int,
  "UserID" int,
  "MessageText" text,
  "CreatedAt" timestamp
);

CREATE TABLE "MessageEdits" (
  "EditID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MessageID" int,
  "EditedText" text,
  "EditedAt" timestamp
);

CREATE TABLE "ChannelSettings" (
  "ChannelID" int PRIMARY KEY,
  "IsArchived" boolean
);

-- Добавляем внешние ключи
ALTER TABLE "UserActivityLogs" ADD FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID");
ALTER TABLE "ChannelMembers" ADD FOREIGN KEY ("ChannelID") REFERENCES "Channels" ("ChannelID");
ALTER TABLE "DirectMessages" ADD FOREIGN KEY ("SenderID") REFERENCES "Users" ("UserID");
ALTER TABLE "MessageEdits" ADD FOREIGN KEY ("MessageID") REFERENCES "Messages" ("MessageID");
ALTER TABLE "Messages" ADD FOREIGN KEY ("ChannelID") REFERENCES "Channels" ("ChannelID");
ALTER TABLE "ChannelSettings" ADD FOREIGN KEY ("ChannelID") REFERENCES "Channels" ("ChannelID");
ALTER TABLE "UserMentions" ADD FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID");
ALTER TABLE "UserRoles" ADD FOREIGN KEY ("RoleID") REFERENCES "AppRoles" ("RoleID");
ALTER TABLE "MessageReactions" ADD FOREIGN KEY ("MessageID") REFERENCES "Messages" ("MessageID");
ALTER TABLE "UserSettings" ADD FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID");
ALTER TABLE "Files" ADD FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID");
ALTER TABLE "UserRoles" ADD FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID");

-- +goose Down
-- Удаляем связи и таблицы в обратном порядке
DROP TABLE IF EXISTS "UserActivityLogs";
DROP TABLE IF EXISTS "ChannelMembers";
DROP TABLE IF EXISTS "UserRoles";
DROP TABLE IF EXISTS "MessageReactions";
DROP TABLE IF EXISTS "DirectMessages";
DROP TABLE IF EXISTS "AppRoles";
DROP TABLE IF EXISTS "Files";
DROP TABLE IF EXISTS "UserSettings";
DROP TABLE IF EXISTS "AppSettings";
DROP TABLE IF EXISTS "FileMessages";
DROP TABLE IF EXISTS "Channels";
DROP TABLE IF EXISTS "UserMentions";
DROP TABLE IF EXISTS "Messages";
DROP TABLE IF EXISTS "MessageEdits";
DROP TABLE IF EXISTS "ChannelSettings";
DROP TABLE IF EXISTS "Users";

-- Удаляем типы
DROP TYPE IF EXISTS usersettings_theme_enum;
DROP TYPE IF EXISTS usersettings_notificationlevel_enum;